### ISSUE TITLE
mDNS and/or DNSSD for rendezvous server

### ISSUE THREAD

**Issue by kraney** [secure-device-onboard/rendezvous-service#7]
It would be very useful in the on-premise case for rendezvous server if the device could find the server using mDNS or DNS service discovery. The user could really just run the rendezvous server on the local subnet long enough for the device to get redirected to the IoT service.

**Comment by trbehera** [comment]
I suppose this is a duplicate. The discussion can continue over the issue filed [here](https://github.com/secure-device-onboard/supply-chain-tools/issues/5).
